#Reload configuration: /bbereload
#or restart server.
#<---- Block drop exp ---->
#id block
#If you do not remove this config ex:
#block-drop-exp-id-99: 46
#block-set-exp-drop-99: 999999

block-drop-exp-id-1: 2
block-set-exp-drop-1: 999

#block-drop-exp-id-2: ID_BLOCK ex: 2
#block-set-exp-drop-2: EXP_DROP ex: 99999

#block-drop-exp-id-3: ID_BLOCK ex: 2
#block-set-exp-drop-3: EXP_DROP ex: 99999

#block-drop-exp-id-4: ID_BLOCK ex: 2
#block-set-exp-drop-4: EXP_DROP ex: 99999

#block-drop-exp-id-5: ID_BLOCK ex: 2
#block-set-exp-drop-5: EXP_DROP ex: 99999

#block-drop-exp-id-6: ID_BLOCK ex: 2
#block-set-exp-drop-6: EXP_DROP ex: 99999

#block-drop-exp-id-7: ID_BLOCK ex: 2
#block-set-exp-drop-7: EXP_DROP ex: 99999

#block-drop-exp-id-8: ID_BLOCK ex: 2
#block-set-exp-drop-8: EXP_DROP ex: 99999

#block-drop-exp-id-9: ID_BLOCK ex: 2
#block-set-exp-drop-9: EXP_DROP ex: 99999

#block-drop-exp-id-10: ID_BLOCK ex: 2
#block-set-exp-drop-10: EXP_DROP ex: 99999

#<---- No Break Block ---->
#If you do not remove this config ex:
#no-break-99: 46
no-break-1: 7
#no-break-2: ID_BLOCK
#no-break-3: ID_BLOCK
#no-break-4: ID_BLOCK
#no-break-5: ID_BLOCK
#no-break-6: ID_BLOCK
#no-break-7: ID_BLOCK
#no-break-8: ID_BLOCK
#no-break-9: ID_BLOCK
#no-break-10: ID_BLOCK

#<---- No Break Block ---->
#If you do not remove this config ex:
#bast-block-type-command-99 133
#bast-block-command-99 logout
bast-block-type-command-1: 57
bast-block-command-1: spawn

#bast-block-type-command-2: ID_BLOCK
#bast-block-command-2: command

#bast-block-type-command-3: ID_BLOCK
#bast-block-command-3: command

#bast-block-type-command-4: ID_BLOCK
#bast-block-command-4: command

#bast-block-type-command-5: ID_BLOCK
#bast-block-command-5: command

#bast-block-type-command-6: ID_BLOCK
#bast-block-command-6: command

#bast-block-type-command-7: ID_BLOCK
#bast-block-command-7: command

#bast-block-type-command-8: ID_BLOCK
#bast-block-command-8: command

#bast-block-type-command-9: ID_BLOCK
#bast-block-command-9: command

#bast-block-type-command-10: ID_BLOCK
#bast-block-command-10: command





